//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiNLine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class board
    {
        public int game { get; set; }
        public int row { get; set; }
        public int column { get; set; }
        public string chipColor { get; set; }
        public string winner { get; set; }
    }
}
